services:
  postgres:
    image: postgres:16
    container_name: postgres_grocery_list
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgresDb:/var/lib/postgresql

  backend:
    build: ./backend
    container_name: grocery_backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    networks:
      - default
      - mailcow_net
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    profiles:
      - local
    container_name: grocery_frontend
    restart: always
    ports:
      - '8083:80'
    depends_on:
      - backend

  frontend_react:
      build: ./frontend_react
      container_name: grocery_frontend_react
      restart: always
      ports:
        - '8083:80'
      depends_on:
        - backend

  mailhog:
    image: mailhog/mailhog
    profiles:
      - local
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgresDb:

networks:
  default:
  mailcow_net:
    external: true
    name: mailcowdockerized_mailcow-network