import React, { useState } from 'react';
import {
    StyleSheet,
    View,
    Text,
    TextInput,
    TouchableOpacity,
    ScrollView,
    ActivityIndicator,
    Alert, Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import {useAuth} from "@/context/authContext";

export default function SetupScreen() {
    const { register, linkWithCode, isLoading } = useAuth();
    const router = useRouter();

    // Form State Fields
    const [isSyncingMode, setIsSyncingMode] = useState(false);
    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [email, setEmail] = useState('');
    const [syncCodeInput, setSyncCodeInput] = useState('');

    const handleRegisterSubmit = async () => {
        const fNameTrimmed = firstName.trim();
        const lNameTrimmed = lastName.trim();
        const emailTrimmed = email.trim();

        if (!fNameTrimmed || !lNameTrimmed || !emailTrimmed.includes('@')) {
            Alert.alert('Validation Error', 'Please complete all fields with a valid email address.');
            return;
        }

        try {
            await register(fNameTrimmed, lNameTrimmed, emailTrimmed);
            router.replace('/drawer/home');
        } catch (error: any) {
            Alert.alert('Registration Failed', error.message || 'Something went wrong.');
        }
    };

    const handleSyncSubmit = async () => {
        const codeTrimmed = syncCodeInput.trim();

        if (!codeTrimmed) {
            Alert.alert('Validation Error', 'Please enter a synchronization code.');
            return;
        }

        try {
            await linkWithCode(codeTrimmed);
            router.replace('/drawer/home');
        } catch (error: any) {
            // Mimics: L10n.of(context, 'sync_error')
            Alert.alert('Sync Error', 'Could not sync account with this code. Verify it and try again.');
        }
    };

    if (isLoading) {
        return (
            <View style={styles.centerContainer}>
                <ActivityIndicator size="large" color="#007AFF" />
            </View>
        );
    }

    return (
        <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
            <View style={styles.logoSection}>
                <Ionicons name="basket" size={90} color="#007AFF" />
                <Text style={styles.title}>
                    {isSyncingMode ? 'Sync Account' : 'Welcome to Grocery Master'}
                </Text>
            </View>

            {!isSyncingMode ? (
                <View style={styles.formContainer}>
                    <Text style={styles.subtitle}>Create an account locally or link an existing group profile to get started.</Text>

                    <Text style={styles.label}>First Name</Text>
                    <TextInput
                        style={styles.input}
                        value={firstName}
                        onChangeText={setFirstName}
                        placeholder="John"
                    />

                    <Text style={styles.label}>Last Name</Text>
                    <TextInput
                        style={styles.input}
                        value={lastName}
                        onChangeText={setLastName}
                        placeholder="Doe"
                    />

                    <Text style={styles.label}>Email Address</Text>
                    <TextInput
                        style={styles.input}
                        value={email}
                        onChangeText={setEmail}
                        placeholder="john.doe@example.com"
                        autoCapitalize="none"
                        keyboardType="email-address"
                    />

                    <TouchableOpacity style={styles.primaryButton} onPress={handleRegisterSubmit}>
                        <Text style={styles.primaryButtonText}>Get Started</Text>
                    </TouchableOpacity>

                    <TouchableOpacity
                        style={styles.linkButton}
                        onPress={() => setIsSyncingMode(true)}
                    >
                        <Text style={styles.linkButtonText}>Already have an account? Sync it</Text>
                    </TouchableOpacity>
                </View>
            ) : (
                <View style={styles.formContainer}>
                    <Text style={styles.subtitle}>Enter the synchronization token generated by your alternate linked mobile terminal node.</Text>

                    <Text style={styles.label}>Sync Code</Text>
                    <TextInput
                        style={[styles.input, styles.codeField]}
                        value={syncCodeInput}
                        onChangeText={setSyncCodeInput}
                        placeholder="Paste code sequence here..."
                        autoCapitalize="none"
                        autoCorrect={false}
                    />

                    <TouchableOpacity style={styles.primaryButton} onPress={handleSyncSubmit}>
                        <Text style={styles.primaryButtonText}>Sync Now</Text>
                    </TouchableOpacity>

                    <TouchableOpacity
                        style={styles.linkButton}
                        onPress={() => setIsSyncingMode(false)}
                    >
                        <Text style={styles.linkButtonText}>Back to registration profile</Text>
                    </TouchableOpacity>
                </View>
            )}
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 24,
        backgroundColor: '#fff',
        justifyContent: 'center',
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    logoSection: {
        alignItems: 'center',
        marginBottom: 32,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1c1c1e',
        marginTop: 16,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 14,
        color: '#8e8e93',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    formContainer: {
        width: '100%',
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1c1c1e',
        marginBottom: 6,
    },
    input: {
        height: 48,
        borderWidth: 1,
        borderColor: '#e5e5ea',
        borderRadius: 8,
        paddingHorizontal: 12,
        fontSize: 16,
        marginBottom: 16,
        backgroundColor: '#fafafa',
    },
    codeField: {
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
        textAlign: 'center',
        fontSize: 15,
        borderStyle: 'dashed',
    },
    primaryButton: {
        backgroundColor: '#007AFF',
        height: 48,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
    },
    primaryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    linkButton: {
        marginTop: 16,
        alignItems: 'center',
    },
    linkButtonText: {
        color: '#007AFF',
        fontSize: 14,
    },
});